### PR TITLE
Implemented the frontend for add-student

### PR DESCRIPTION
**Pull request by nasieraghafar**
Had manually tested the add student feature with both frontend and backend

### CODE REVIEW

**Review by Lachyland — CHANGES_REQUESTED** [review]
Possible to add a banner for the css part to add improvement

**Comment by nasieraghafar** [comment]
I have implemented the addition of the student management banner at the top of index.html. please review

**Review by mdtfir — APPROVED** [review]
lgtm approved

**Review by Lachyland — APPROVED** [review]
lgtm

**Pull request merged**
