### PR TITLE
Add Read feature implemented

### PR DESCRIPTION
**Pull request by Lachyland**
Had manually tested the read feature and implemented the frontend

### CODE REVIEW

**Comment by nasieraghafar** [comment]
the table should have a edit button and a way to add students

**Comment by Lachyland** [comment]
Implemented add button and update button. Please review!

**Comment by nasieraghafar** [comment]
lgtm

**Review by nasieraghafar — APPROVED** [review]
lgtm. can proceed

**Comment by mdtfir** [comment]
lgtm.

**Review by mdtfir — APPROVED** [review]
lgtm

**Pull request merged**
